project:
  type: website
  output-dir: docs #where files are rendered to

website:
  title: "terradressler.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true #table of contents

editor: visual

